$! -*- mode: html-helper; -*- !$
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
<link href="$page.relativeRoot$/cssjs/style.css" media="screen" rel="stylesheet" type="text/css"></link>
<link href="$page.relativeRoot$/cssjs/common.css" media="screen" rel="stylesheet" type="text/css"></link>
<link href="$page.relativeRoot$/cssjs/lytebox/lytebox.css" media="screen" rel="stylesheet" type="text/css"></link>
<script src="$page.relativeRoot$/cssjs/lytebox/lytebox.js" language="javascript" type="text/javascript"></script>
<title>$custom.blogname$: $if (page.title)$$page.title$$endif$</title>
</head>
