$! -*- mode: nxml; -*- !$

  <item>
    <title>$article.title$</title>
    <link>$custom.blogurl$id/$article.fileName$</link>
    <guid>"$custom.blogurl$id/$article.fileName$"></guid>
    <pubDate>$article.date; format="yyyy-MM-d'T'HH:mm:ssZ"$</pubDate>
    <description>
<![CDATA[
$article.content$</div>
]]>
    </description>
    <author>Brian M. Clapper &lt;bmc@clapper.org&gt;</author>
  </item>
